version: '3.5'

# This files serves as filesystem anchor
# Including it as first .yml file makes all build paths relative to this directory ('docker')
#
# Examples:
#
# Build all components comprising Kafka, Zookeeper and Keycloak
# docker-compose -f compose.yml -f kafka/compose-all.yml up --build